Repository dirk-thomas/vcstool, pull requests merged in 2021-04, with the labels that each got.

#206 Fix #205: `--recursive` is not recursive
  vcstool/clients/git.py
Labels: bug

#203 Detect special POSIX shells on Windows and output POSIX paths
  vcstool/executor.py
Labels: bug, enhancement

#171 support git version starting with heads/ or tags/
  test/import.txt
  test/import_shallow.txt
  test/list.repos
  test/test_commands.py
  test/validate.txt
  vcstool/clients/git.py
Labels: enhancement
